_target_: warprl.algorithms.shac.SHAC
_recursive_: False

actor_config:
  _target_: warprl.models.actor.ActorStochasticMLP
  units: [400, 200, 100]
  activation_class: nn.Mish
  init_gain: 1.0
  init_logstd: -1.0

critic_config:
  _target_: warprl.models.critic.CriticMLP
  units: [400, 200]
  activation_class: nn.Mish

num_critics: 3
actor_lr: 2e-3
critic_lr: 5e-4
lr_schedule: linear
obs_rms: True
ret_rms: True
critic_iterations: 16
critic_batches: 4
critic_method: td-lambda # ('td-lambda', 'one-step')
lam: 0.95
gamma: 0.99
max_epochs: 2000
horizon: 32
actor_grad_norm: 1.0 # Can also be none
critic_grad_norm: 100.0 # Can also be none
save_interval: 400
device: ${general.device}
