config:
  _target_: pwm.envs.allegro_hand.AllegroHandEnv
  visualize: ${general.visualize}
  device: ${general.device}
  num_envs: 16
  fps: 60
  substeps: 16
  episode_length: 1000
  stochastic_init: True
  no_grad: False
  MM_caching_frequency: 48
  early_termination: True
  action_scale: 0.2
  action_strength: 20.0
  action_penalty: -0.002
  height_rew_scale: 10.0
  joint_vel_obs_scaling: 0.1
  termination_height: 0.74
  termination_tolerance: 0.1
  up_rew_scale: 10.0

shac:
  actor_lr: 2e-3
  critic_lr: 5e-4
  max_epochs: 3000
  save_interval: 500
  actor_mlp:
    units: [400, 200, 100]
  critic_mlp:
    units: [400, 200]
